config/routes.rb
Rails.application.routes.draw do

  get "/about" => "home#about"
  get "/posts/index2" => "posts#index2"
  get "/posts/new2" => "posts#new2"
  get "/posts/create" => "posts#create2"
  resources :posts
  resources :writes
  get "posts/:id/update" => "posts#update"


  root "home#top"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/write.rb
class Write < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def index2
    @posts = Post.all.order(created_at: :desc)
  end

  def show
    @post = Post.find_by(id: params[:id])
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def create
    @post = Post.new(content: params[:content])
    @post.save
    redirect_to posts_path
  end

  def create2
    @post = Post.new(title: params[:title])
    @post.save
    redirect_to posts_index2_path
  end

  def new
    @post = Post.new
  end

  def new2
    @post = Post.new
  end

  def update
    @post = Post.find_by(id: params[:id])
    @post.update(content: params[:content])
    @post.save
    redirect_to posts_path
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    redirect_to posts_path
  end

private
  def post_params
    params.require(:post).permit(:title, :content)
  end

end

app/controllers/writes_controller.rb
class WritesController < ApplicationController
  def index
    @writes = Write.all.order(created_at: :desc)
  end

  def index2
    @writes = Write.all.order(created_at: :desc)
  end

  def show
    @write = Write.find_by(id: params[:id])
  end

  def edit
    @write = Write.find_by(id: params[:id])
  end

  def create
    @write = Write.new(content: params[:content])
    @write.save
    redirect_to writes_path
  end

  def create2
    @write = Write.new(title: params[:title])
    @write.save
    redirect_to writes_index2_path
  end

  def new
    @write = Write.new
  end

  def new2
    @write = Write.new
  end

  def update
    @write = Write.find_by(id: params[:id])
    @write.update(content: params[:content])
    @write.save
    redirect_to writes_path
  end

  def destroy
    @write = Write.find_by(id: params[:id])
    @write.destroy
    redirect_to writes_path
  end

private
  def write_params
    params.require(:write).permit(:title, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/writes_helper.rb
module WritesHelper
end

app/views/home/about.html.erb
    <div class="about-main">
      <h2>後悔しない生き方とは</h2>
        <ul>
          <li>自分らしく生きる</li>
          <li>したいこと、目標を明確にする</li>
          <li>学んだことを行動にする</li>
          <li>健康に生きる</li>
        </ul>
    </div>

app/views/home/top.html.erb
<html lang="ja">
<head>
	<meta charset="utf-8">
	<meta name="X-UA-Compatible" content="IE=Edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Bootstrap-slider</title>

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>

	<div class="worksslider inside">
		<div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="3000">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag "haikei.jpg" %>
      <div class="carousel-caption">

      </div>
    </div>
    <div class="item">
      <%= image_tag "haikei1.jpg" %>
      <div class="carousel-caption">

      </div>
    </div>
    <div class="item">
      <%= image_tag "haikei2.jpg"%>
      <div class="carousel-caption">

      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
	</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
    <title>Todo2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/ >
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <header>
  <div class="header-logo">
      <%= link_to "人生の目標", "/" %>
  </div>
  <ul class = "header-menus">
    <li>
      <%= link_to "トップへ", "/" %>
    </li>
    <li>
      <%= link_to "後悔しない生き方とは","/about" %>
    </li>
    <li>
      <%= link_to "今日までに", posts_path %>
    </li>
    <li>
      <%= link_to "理想の暮らし",writes_path %>
    </li>

  </ul>
</header>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">編集する</h1>
    <%= form_for @post do |f| %>
    <div class="form">
      <div class="form-body">
        <textarea name = "content"><%= @post.content %></textarea>
        <input type="submit" value="保存">
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="main posts-index">
  <div class="container">
    <% @posts.each do |post| %>
      <div class="posts-index-item">
        <%= link_to post.content, post_path(post) %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index2.html.erb
<div class="main posts-index">
  <div class="container">
    <% @posts.each do |post| %>
      <div class="posts-index-item">
        <%= link_to post.title, post_path(post) %>
      </div>
    <% end %>
    <%= link_to "新規投稿", "/posts/new2", class: "new-post" %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">投稿する</h1>
    <%= form_for @post do |f| %>
    <div class="form">
      <div class="form-body">
        <textarea name = "content"></textarea>
        <input type="submit" value="投稿">
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/new2.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">投稿する</h1>
    <%= form_for @post ,url: posts_path, method: :post do |f| %>
    <div class="form">
      <div class="form-body">
        <textarea name = "title"></textarea>
        <input type="submit" value="投稿">
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="main posts-show">
  <div class="container">
    <div class="posts-show-item">
      <p>
        <%= @post.content %>
      </p>
      <div class="post-time">
        <%= @post.created_at %>
      </div>
        <div class="post-menus">
        <%= link_to "編集", edit_post_path %>
        <%= link_to "削除する", post_path, method: :delete,data:{confirm:"本当によろしいですか？"} %>
      </div>
    </div>
  </div>
</div>

app/views/writes/edit.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">編集する</h1>
    <%= form_for @write do |f| %>
    <div class="form">
      <div class="form-body">
        <textarea name = "content"><%= @write.content %></textarea>
        <input type="submit" value="保存">
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/writes/index.html.erb
<div class="main posts-index">
  <div class="container">
    <h1>理想の暮らし</h1>
    <% @writes.each do |write| %>
      <div class="posts-index-item">
        <%= check_box_tag :sample %>
        <%= label_tag %>
        <%= link_to write.content, write_path(write) %>
      </div>
    <% end %>
    <%= link_to "新規投稿", new_write_path, class: "new-post" %>
  </div>
</div>

app/views/writes/new.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">投稿する</h1>
    <%= form_for @write do |f| %>
    <div class="form">
      <div class="form-body">
        <textarea name = "content"></textarea>
        <input type="submit" value="投稿">
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/writes/show.html.erb
<div class="main posts-show">
  <div class="container">
    <div class="posts-show-item">
      <p>
        <%= @write.content %>
      </p>
      <div class="post-time">
        <%= @write.created_at %>
      </div>
        <div class="post-menus">
        <%= link_to "編集", edit_write_path %>
        <%= link_to "削除する", write_path, method: :delete,data:{confirm:"本当によろしいですか？"} %>
      </div>
    </div>
  </div>
</div>